---
# InputFileDir: E:/media/zgv/backups-april2022/
# InputFileDir: E:/media/zgv/backups-sept-2022/
# InputFileDir: /home/ec2-user/video/input/
# InputFileDir: C:/video/lossless/
InputFileDir: D:/rawvideo/
InputFilename: 2022-11-24_09-56-41
# InputExtension: '.mp4'
# InputExtension: '.webm'
InputExtension: '.avi'

OutFileDir: C:/video/py_vp9/
# OutFileDir: /home/ec2-user/video/input/
# OutFileDir: D:/renders/
NewOutputFolder: 'gerudo-gate-rerecord'
OutputExtension: '.webm'
# OutputCodec: 'libvpx'
OutputCodec: 'libvpx-vp9'

StripAudio: false

TrimVideo: true
TrimStart: '00:00:00.633'
TrimVideoEnd: false
TrimEnd: '00:00:00.000'

Scale: true
ScaleMode: neighbor
OutResolution: 320x240
# OutResolution: 640x480

SetPixelFormat: true
PixelFormat: yuv444p
PixelFormats:
  - 'yuv444p'
  - 'yuv420p'

UseDeadline: false
Deadline: 'best'
# Deadline: 'good'

Batch: true
CRFDefault: '20'
CRF: #batch mode crf
  - '50'
  - '40'
  - '30'
  - '20'
  - '10'
  - '0'

BatchOutputResolutions:
  - '320x240'
  - '640x480'
  # - '960x720'
  # - '1280x960'
  # - '1600x1200'
  # - '1920x1440'
  # - '2240x1680'
  # - '2560x1920'
  # - '2560x1920'
  # - '2880x2160'

BatchCodecs:
  - 'libx264'
  - 'libvpx-vp9'

Debug: true

CreateImages: true

#extra flags: print commands but do not run
SkipEncoding: false
SkipImages: false

RunOCR: true
EncodeSlideshow: true
# Bug- video encodes infinitely before even hitting the ss folder
