---
InputFileDir: C:/video/lossless/
# InputFileDir: C:/video/releaseOBS/
InputFilename: 2022-02-05_16-36-58
# InputExtension: '.mp4'
InputExtension: '.avi'

OutFileDir: C:/video/
NewOutputFolder: 'hf-redo2'
OutputExtension: '.webm'
# OutputCodec: 'libvpx'
OutputCodec: 'libvpx-vp9'

StripAudio: false
TrimVideo: true
TrimStart: '00:00:00.186'
TrimVideoEnd: false
TrimEnd: '00:00:00.000'

Scale: true
ScaleMode: neighbor
OutResolution: 320x240
# OutResolution: 640x480

SetPixelFormatWhenScaling: true
PixelFormat: yuv444p
# PixelFormat: yuv420p

UseDeadline: false
Deadline: 'best'
# Deadline: 'good'

Batch: true
CRFDefault: '20'
CRF: #batch mode crf
  - '50'
  - '40'
  - '30'
  - '20'
  - '10'
  # - '0'

BatchOutputResolutions:
  - 'default'
  - '320x240'
  # - '313x237'

BatchCodecs:
  # - 'libvpx'
  - 'libvpx-vp9'

CreateImages: true

Debug: true
SkipEncoding: false
SkipImages: false
