---
InputFilename: 2021-10-26_18-46-11
InputExtension: '.mp4'
OutputExtension: '.webm'
FileDir: C:/video/releaseOBS/
FolderDir: C:/Users/Saturn/Videos/
Debug: true
SkipEncoding: false
Batch: false
Scale: true
ScaleMode: lanczos
Environment: dev
Mode: file
OutFileDir: C:/video/
OutFolderDir: C:/video/
OutResolution: 640x480
CRFDefault: '26'
CRF:
  - '50'
  - '30'
  - '20'
  - '12'
  - '8'
