---
InputFileDir: C:/video/lossless/
# InputFileDir: C:/video/releaseOBS/
InputFilename: 2022-04-05_21-31-13
# InputExtension: '.mp4'
InputExtension: '.avi'

OutFileDir: C:/video/
NewOutputFolder: 'output'
OutputExtension: '.webm'
# OutputCodec: 'libvpx'
OutputCodec: 'libvpx-vp9'

StripAudio: true
TrimVideo: false
TrimStart: '00:00:00.000'
TrimVideoEnd: false
TrimEnd: '00:00:00.000'

Scale: true
ScaleMode: neighbor
OutResolution: 320x240
# OutResolution: 640x480

UseDeadline: false
Deadline: 'best'
# Deadline: 'good'

Batch: true
CRFDefault: '20'
CRF: #batch mode crf
  # - '48'
  # - '42'
  # - '36'
  # - '30'
  # - '26'
  - '14'
  - '8'

BatchOutputResolutions:
  - 'default'
  - '320x240'
  # - '313x237'

BatchCodecs:
  # - 'libvpx'
  - 'libvpx-vp9'

CreateImages: true

Debug: true
SkipEncoding: false
SkipImages: false
