---
InputFileDir: C:/video/lossless/
# InputFileDir: C:/video/releaseOBS/
# InputFilename: 2021-10-26_18-46-11
InputFilename: 2022-02-06_11-56-02
# InputExtension: '.mp4'
InputExtension: '.avi'

OutFileDir: C:/video/
OutputExtension: '.webm'

StripAudio: true
TrimVideo: false
TrimStart: '00:00:00.182'
Scale: true
ScaleMode: neighbor
OutResolution: 320x240
# OutResolution: 320x240
# OutResolution: 640x480
# OutResolution: 960x720
# OutResolution: 1280x960

Batch: true
CRFDefault: '20'
CRF: #batch mode crf
  - '50'
  - '30'
  - '20'
  - '12'
  - '8'

BatchOutputResolutions:
  - 'default'
  - '320x240'

UseDeadline: true
Deadline: 'best' 
# Deadline: 'good' # use this one to make speed more reasonable

Debug: true
SkipEncoding: true
