---
InputFileDir: C:/video/releaseOBS/
InputFilename: 2021-10-26_18-46-11
InputExtension: '.mp4'
OutFileDir: C:/video/
OutputExtension: '.webm'
Scale: true
OutResolution: 640x480
# OutResolution: 640x480
# OutResolution: 960x720
# OutResolution: 1280x960
ScaleMode: lanczos
Batch: false
CRFDefault: '26'
CRF:
  - '50'
  - '30'
  - '20'
  - '12'
  - '8'
Debug: true
SkipEncoding: false