---
# InputFileDir: C:/video/lossless/
InputFileDir: /home/ec2-user/video/input/
InputFilename: 2022-08-26_17-16-46
# InputExtension: '.mp4'
InputExtension: '.avi'

# OutFileDir: C:/video/py_vp9/
OutFileDir: /home/ec2-user/video/input/
NewOutputFolder: 'kz-ambience2'
OutputExtension: '.webm'
# OutputCodec: 'libvpx'
OutputCodec: 'libvpx-vp9'

StripAudio: false
TrimVideo: true
TrimStart: '00:00:00.000'
TrimVideoEnd: false
TrimEnd: '00:00:00.000'

Scale: true
ScaleMode: neighbor
OutResolution: 320x240
# OutResolution: 640x480

SetPixelFormat: true
PixelFormat: yuv444p
PixelFormats:
  - 'yuv444p'
  - 'yuv420p'

UseDeadline: false
Deadline: 'best'
# Deadline: 'good'

Batch: true
CRFDefault: '20'
CRF: #batch mode crf
  # - '50'
  # - '40'
  - '30'
  # - '20'
  # - '10'
  # - '0'

BatchOutputResolutions:
  # - 'default'
  - '320x240'
  # - '313x237'

BatchCodecs:
  # - 'libvpx'
  - 'libx264'
  - 'libvpx-vp9'

Debug: true
SkipEncoding: false

CreateImages: true
#extra flag: generate commands but do not execute
SkipImages: true
